# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
  
    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: application/${{ matrix.project }}
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: application/${{ matrix.project }}/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      
  build:
    needs: test
    strategy:
      matrix:
        build: [frontend, api, db-seed]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: application/${{ matrix.project }}
  
    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t ${{ matrix.build }}
      
    - uses: azure/docker-login@v1
      with:
        login-server: teilchenmanual.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t teilchenmanual.azurecr.io/${{ matrix.build }}:${{ github.sha }}
        docker push teilchenmanual.azurecr.io/${{ matrix.build }}:${{ github.sha }}
      working-directory: application/${{ matrix.build }}
      
